// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// URLColumns holds the columns for the "url" table.
	URLColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "expire_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// URLTable holds the schema information for the "url" table.
	URLTable = &schema.Table{
		Name:       "url",
		Columns:    URLColumns,
		PrimaryKey: []*schema.Column{URLColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		URLTable,
	}
)

func init() {
	URLTable.Annotation = &entsql.Annotation{
		Table: "url",
	}
}
