// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/long2ice/longurl/ent/migrate"

	"github.com/long2ice/longurl/ent/url"
	"github.com/long2ice/longurl/ent/visitlog"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Url is the client for interacting with the Url builders.
	Url *UrlClient
	// VisitLog is the client for interacting with the VisitLog builders.
	VisitLog *VisitLogClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Url = NewUrlClient(c.config)
	c.VisitLog = NewVisitLogClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Url:      NewUrlClient(cfg),
		VisitLog: NewVisitLogClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Url:      NewUrlClient(cfg),
		VisitLog: NewVisitLogClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Url.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Url.Use(hooks...)
	c.VisitLog.Use(hooks...)
}

// UrlClient is a client for the Url schema.
type UrlClient struct {
	config
}

// NewUrlClient returns a client for the Url from the given config.
func NewUrlClient(c config) *UrlClient {
	return &UrlClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `url.Hooks(f(g(h())))`.
func (c *UrlClient) Use(hooks ...Hook) {
	c.hooks.Url = append(c.hooks.Url, hooks...)
}

// Create returns a create builder for Url.
func (c *UrlClient) Create() *URLCreate {
	mutation := newURLMutation(c.config, OpCreate)
	return &URLCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Url entities.
func (c *UrlClient) CreateBulk(builders ...*URLCreate) *URLCreateBulk {
	return &URLCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Url.
func (c *UrlClient) Update() *URLUpdate {
	mutation := newURLMutation(c.config, OpUpdate)
	return &URLUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UrlClient) UpdateOne(u *Url) *URLUpdateOne {
	mutation := newURLMutation(c.config, OpUpdateOne, withUrl(u))
	return &URLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UrlClient) UpdateOneID(id int) *URLUpdateOne {
	mutation := newURLMutation(c.config, OpUpdateOne, withUrlID(id))
	return &URLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Url.
func (c *UrlClient) Delete() *URLDelete {
	mutation := newURLMutation(c.config, OpDelete)
	return &URLDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UrlClient) DeleteOne(u *Url) *URLDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UrlClient) DeleteOneID(id int) *URLDeleteOne {
	builder := c.Delete().Where(url.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &URLDeleteOne{builder}
}

// Query returns a query builder for Url.
func (c *UrlClient) Query() *URLQuery {
	return &URLQuery{
		config: c.config,
	}
}

// Get returns a Url entity by its id.
func (c *UrlClient) Get(ctx context.Context, id int) (*Url, error) {
	return c.Query().Where(url.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UrlClient) GetX(ctx context.Context, id int) *Url {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLogs queries the logs edge of a Url.
func (c *UrlClient) QueryLogs(u *Url) *VisitLogQuery {
	query := &VisitLogQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(url.Table, url.FieldID, id),
			sqlgraph.To(visitlog.Table, visitlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, url.LogsTable, url.LogsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UrlClient) Hooks() []Hook {
	return c.hooks.Url
}

// VisitLogClient is a client for the VisitLog schema.
type VisitLogClient struct {
	config
}

// NewVisitLogClient returns a client for the VisitLog from the given config.
func NewVisitLogClient(c config) *VisitLogClient {
	return &VisitLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `visitlog.Hooks(f(g(h())))`.
func (c *VisitLogClient) Use(hooks ...Hook) {
	c.hooks.VisitLog = append(c.hooks.VisitLog, hooks...)
}

// Create returns a create builder for VisitLog.
func (c *VisitLogClient) Create() *VisitLogCreate {
	mutation := newVisitLogMutation(c.config, OpCreate)
	return &VisitLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VisitLog entities.
func (c *VisitLogClient) CreateBulk(builders ...*VisitLogCreate) *VisitLogCreateBulk {
	return &VisitLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VisitLog.
func (c *VisitLogClient) Update() *VisitLogUpdate {
	mutation := newVisitLogMutation(c.config, OpUpdate)
	return &VisitLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VisitLogClient) UpdateOne(vl *VisitLog) *VisitLogUpdateOne {
	mutation := newVisitLogMutation(c.config, OpUpdateOne, withVisitLog(vl))
	return &VisitLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VisitLogClient) UpdateOneID(id int) *VisitLogUpdateOne {
	mutation := newVisitLogMutation(c.config, OpUpdateOne, withVisitLogID(id))
	return &VisitLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VisitLog.
func (c *VisitLogClient) Delete() *VisitLogDelete {
	mutation := newVisitLogMutation(c.config, OpDelete)
	return &VisitLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VisitLogClient) DeleteOne(vl *VisitLog) *VisitLogDeleteOne {
	return c.DeleteOneID(vl.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VisitLogClient) DeleteOneID(id int) *VisitLogDeleteOne {
	builder := c.Delete().Where(visitlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VisitLogDeleteOne{builder}
}

// Query returns a query builder for VisitLog.
func (c *VisitLogClient) Query() *VisitLogQuery {
	return &VisitLogQuery{
		config: c.config,
	}
}

// Get returns a VisitLog entity by its id.
func (c *VisitLogClient) Get(ctx context.Context, id int) (*VisitLog, error) {
	return c.Query().Where(visitlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VisitLogClient) GetX(ctx context.Context, id int) *VisitLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryURL queries the url edge of a VisitLog.
func (c *VisitLogClient) QueryURL(vl *VisitLog) *URLQuery {
	query := &URLQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := vl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(visitlog.Table, visitlog.FieldID, id),
			sqlgraph.To(url.Table, url.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, visitlog.URLTable, visitlog.URLColumn),
		)
		fromV = sqlgraph.Neighbors(vl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VisitLogClient) Hooks() []Hook {
	return c.hooks.VisitLog
}
