// Code generated by entc, DO NOT EDIT.

package ent

import (
	"long2ice/longurl/ent/schema"
	"long2ice/longurl/ent/url"
	"long2ice/longurl/ent/visitlog"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlFields := schema.Url{}.Fields()
	_ = urlFields
	// urlDescURL is the schema descriptor for url field.
	urlDescURL := urlFields[0].Descriptor()
	// url.URLValidator is a validator for the "url" field. It is called by the builders before save.
	url.URLValidator = urlDescURL.Validators[0].(func(string) error)
	// urlDescPath is the schema descriptor for path field.
	urlDescPath := urlFields[1].Descriptor()
	// url.PathValidator is a validator for the "path" field. It is called by the builders before save.
	url.PathValidator = urlDescPath.Validators[0].(func(string) error)
	// urlDescCreatedAt is the schema descriptor for created_at field.
	urlDescCreatedAt := urlFields[3].Descriptor()
	// url.DefaultCreatedAt holds the default value on creation for the created_at field.
	url.DefaultCreatedAt = urlDescCreatedAt.Default.(func() time.Time)
	visitlogFields := schema.VisitLog{}.Fields()
	_ = visitlogFields
	// visitlogDescCreatedAt is the schema descriptor for created_at field.
	visitlogDescCreatedAt := visitlogFields[9].Descriptor()
	// visitlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	visitlog.DefaultCreatedAt = visitlogDescCreatedAt.Default.(func() time.Time)
}
