// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"long2ice/longurl/ent/url"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLCreate is the builder for creating a Url entity.
type URLCreate struct {
	config
	mutation *URLMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (uc *URLCreate) SetURL(s string) *URLCreate {
	uc.mutation.SetURL(s)
	return uc
}

// SetPath sets the "path" field.
func (uc *URLCreate) SetPath(s string) *URLCreate {
	uc.mutation.SetPath(s)
	return uc
}

// SetExpireAt sets the "expire_at" field.
func (uc *URLCreate) SetExpireAt(t time.Time) *URLCreate {
	uc.mutation.SetExpireAt(t)
	return uc
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableExpireAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetExpireAt(*t)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *URLCreate) SetCreatedAt(t time.Time) *URLCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableCreatedAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// Mutation returns the URLMutation object of the builder.
func (uc *URLCreate) Mutation() *URLMutation {
	return uc.mutation
}

// Save creates the Url in the database.
func (uc *URLCreate) Save(ctx context.Context) (*Url, error) {
	var (
		err  error
		node *Url
	)
	uc.defaults()
	if len(uc.hooks) == 0 {
		if err = uc.check(); err != nil {
			return nil, err
		}
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*URLMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uc.check(); err != nil {
				return nil, err
			}
			uc.mutation = mutation
			if node, err = uc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			if uc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *URLCreate) SaveX(ctx context.Context) *Url {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *URLCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *URLCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *URLCreate) defaults() {
	if _, ok := uc.mutation.CreatedAt(); !ok {
		v := url.DefaultCreatedAt()
		uc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *URLCreate) check() error {
	if _, ok := uc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "url"`)}
	}
	if v, ok := uc.mutation.URL(); ok {
		if err := url.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "url": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "path"`)}
	}
	if v, ok := uc.mutation.Path(); ok {
		if err := url.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "path": %w`, err)}
		}
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	return nil
}

func (uc *URLCreate) sqlSave(ctx context.Context) (*Url, error) {
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uc *URLCreate) createSpec() (*Url, *sqlgraph.CreateSpec) {
	var (
		_node = &Url{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: url.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: url.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: url.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := uc.mutation.Path(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: url.FieldPath,
		})
		_node.Path = value
	}
	if value, ok := uc.mutation.ExpireAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: url.FieldExpireAt,
		})
		_node.ExpireAt = &value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: url.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	return _node, _spec
}

// URLCreateBulk is the builder for creating many Url entities in bulk.
type URLCreateBulk struct {
	config
	builders []*URLCreate
}

// Save creates the Url entities in the database.
func (ucb *URLCreateBulk) Save(ctx context.Context) ([]*Url, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*Url, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*URLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *URLCreateBulk) SaveX(ctx context.Context) []*Url {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *URLCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *URLCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
