// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/long2ice/longurl/ent/predicate"
	"github.com/long2ice/longurl/ent/url"
	"github.com/long2ice/longurl/ent/visitlog"
)

// VisitLogQuery is the builder for querying VisitLog entities.
type VisitLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VisitLog
	// eager-loading edges.
	withURL *URLQuery
	withFKs bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VisitLogQuery builder.
func (vlq *VisitLogQuery) Where(ps ...predicate.VisitLog) *VisitLogQuery {
	vlq.predicates = append(vlq.predicates, ps...)
	return vlq
}

// Limit adds a limit step to the query.
func (vlq *VisitLogQuery) Limit(limit int) *VisitLogQuery {
	vlq.limit = &limit
	return vlq
}

// Offset adds an offset step to the query.
func (vlq *VisitLogQuery) Offset(offset int) *VisitLogQuery {
	vlq.offset = &offset
	return vlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vlq *VisitLogQuery) Unique(unique bool) *VisitLogQuery {
	vlq.unique = &unique
	return vlq
}

// Order adds an order step to the query.
func (vlq *VisitLogQuery) Order(o ...OrderFunc) *VisitLogQuery {
	vlq.order = append(vlq.order, o...)
	return vlq
}

// QueryURL chains the current query on the "url" edge.
func (vlq *VisitLogQuery) QueryURL() *URLQuery {
	query := &URLQuery{config: vlq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(visitlog.Table, visitlog.FieldID, selector),
			sqlgraph.To(url.Table, url.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, visitlog.URLTable, visitlog.URLColumn),
		)
		fromU = sqlgraph.SetNeighbors(vlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VisitLog entity from the query.
// Returns a *NotFoundError when no VisitLog was found.
func (vlq *VisitLogQuery) First(ctx context.Context) (*VisitLog, error) {
	nodes, err := vlq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{visitlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vlq *VisitLogQuery) FirstX(ctx context.Context) *VisitLog {
	node, err := vlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VisitLog ID from the query.
// Returns a *NotFoundError when no VisitLog ID was found.
func (vlq *VisitLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vlq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{visitlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vlq *VisitLogQuery) FirstIDX(ctx context.Context) int {
	id, err := vlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VisitLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VisitLog entity is found.
// Returns a *NotFoundError when no VisitLog entities are found.
func (vlq *VisitLogQuery) Only(ctx context.Context) (*VisitLog, error) {
	nodes, err := vlq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{visitlog.Label}
	default:
		return nil, &NotSingularError{visitlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vlq *VisitLogQuery) OnlyX(ctx context.Context) *VisitLog {
	node, err := vlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VisitLog ID in the query.
// Returns a *NotSingularError when more than one VisitLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (vlq *VisitLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vlq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = &NotSingularError{visitlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vlq *VisitLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := vlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VisitLogs.
func (vlq *VisitLogQuery) All(ctx context.Context) ([]*VisitLog, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vlq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vlq *VisitLogQuery) AllX(ctx context.Context) []*VisitLog {
	nodes, err := vlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VisitLog IDs.
func (vlq *VisitLogQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vlq.Select(visitlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vlq *VisitLogQuery) IDsX(ctx context.Context) []int {
	ids, err := vlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vlq *VisitLogQuery) Count(ctx context.Context) (int, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vlq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vlq *VisitLogQuery) CountX(ctx context.Context) int {
	count, err := vlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vlq *VisitLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vlq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vlq *VisitLogQuery) ExistX(ctx context.Context) bool {
	exist, err := vlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VisitLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vlq *VisitLogQuery) Clone() *VisitLogQuery {
	if vlq == nil {
		return nil
	}
	return &VisitLogQuery{
		config:     vlq.config,
		limit:      vlq.limit,
		offset:     vlq.offset,
		order:      append([]OrderFunc{}, vlq.order...),
		predicates: append([]predicate.VisitLog{}, vlq.predicates...),
		withURL:    vlq.withURL.Clone(),
		// clone intermediate query.
		sql:    vlq.sql.Clone(),
		path:   vlq.path,
		unique: vlq.unique,
	}
}

// WithURL tells the query-builder to eager-load the nodes that are connected to
// the "url" edge. The optional arguments are used to configure the query builder of the edge.
func (vlq *VisitLogQuery) WithURL(opts ...func(*URLQuery)) *VisitLogQuery {
	query := &URLQuery{config: vlq.config}
	for _, opt := range opts {
		opt(query)
	}
	vlq.withURL = query
	return vlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Platform string `json:"platform,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VisitLog.Query().
//		GroupBy(visitlog.FieldPlatform).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (vlq *VisitLogQuery) GroupBy(field string, fields ...string) *VisitLogGroupBy {
	group := &VisitLogGroupBy{config: vlq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vlq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Platform string `json:"platform,omitempty"`
//	}
//
//	client.VisitLog.Query().
//		Select(visitlog.FieldPlatform).
//		Scan(ctx, &v)
//
func (vlq *VisitLogQuery) Select(fields ...string) *VisitLogSelect {
	vlq.fields = append(vlq.fields, fields...)
	return &VisitLogSelect{VisitLogQuery: vlq}
}

func (vlq *VisitLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vlq.fields {
		if !visitlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vlq.path != nil {
		prev, err := vlq.path(ctx)
		if err != nil {
			return err
		}
		vlq.sql = prev
	}
	return nil
}

func (vlq *VisitLogQuery) sqlAll(ctx context.Context) ([]*VisitLog, error) {
	var (
		nodes       = []*VisitLog{}
		withFKs     = vlq.withFKs
		_spec       = vlq.querySpec()
		loadedTypes = [1]bool{
			vlq.withURL != nil,
		}
	)
	if vlq.withURL != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, visitlog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &VisitLog{config: vlq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := vlq.withURL; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*VisitLog)
		for i := range nodes {
			if nodes[i].url_logs == nil {
				continue
			}
			fk := *nodes[i].url_logs
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(url.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "url_logs" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.URL = n
			}
		}
	}

	return nodes, nil
}

func (vlq *VisitLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vlq.querySpec()
	_spec.Node.Columns = vlq.fields
	if len(vlq.fields) > 0 {
		_spec.Unique = vlq.unique != nil && *vlq.unique
	}
	return sqlgraph.CountNodes(ctx, vlq.driver, _spec)
}

func (vlq *VisitLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vlq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (vlq *VisitLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   visitlog.Table,
			Columns: visitlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: visitlog.FieldID,
			},
		},
		From:   vlq.sql,
		Unique: true,
	}
	if unique := vlq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vlq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visitlog.FieldID)
		for i := range fields {
			if fields[i] != visitlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vlq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vlq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vlq *VisitLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vlq.driver.Dialect())
	t1 := builder.Table(visitlog.Table)
	columns := vlq.fields
	if len(columns) == 0 {
		columns = visitlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vlq.sql != nil {
		selector = vlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vlq.unique != nil && *vlq.unique {
		selector.Distinct()
	}
	for _, p := range vlq.predicates {
		p(selector)
	}
	for _, p := range vlq.order {
		p(selector)
	}
	if offset := vlq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vlq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VisitLogGroupBy is the group-by builder for VisitLog entities.
type VisitLogGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vlgb *VisitLogGroupBy) Aggregate(fns ...AggregateFunc) *VisitLogGroupBy {
	vlgb.fns = append(vlgb.fns, fns...)
	return vlgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vlgb *VisitLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vlgb.path(ctx)
	if err != nil {
		return err
	}
	vlgb.sql = query
	return vlgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vlgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VisitLogGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) StringsX(ctx context.Context) []string {
	v, err := vlgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vlgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) StringX(ctx context.Context) string {
	v, err := vlgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VisitLogGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) IntsX(ctx context.Context) []int {
	v, err := vlgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vlgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) IntX(ctx context.Context) int {
	v, err := vlgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VisitLogGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vlgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vlgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vlgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VisitLogGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vlgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VisitLogGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vlgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vlgb *VisitLogGroupBy) BoolX(ctx context.Context) bool {
	v, err := vlgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vlgb *VisitLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vlgb.fields {
		if !visitlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vlgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vlgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vlgb *VisitLogGroupBy) sqlQuery() *sql.Selector {
	selector := vlgb.sql.Select()
	aggregation := make([]string, 0, len(vlgb.fns))
	for _, fn := range vlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vlgb.fields)+len(vlgb.fns))
		for _, f := range vlgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vlgb.fields...)...)
}

// VisitLogSelect is the builder for selecting fields of VisitLog entities.
type VisitLogSelect struct {
	*VisitLogQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vls *VisitLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vls.prepareQuery(ctx); err != nil {
		return err
	}
	vls.sql = vls.VisitLogQuery.sqlQuery(ctx)
	return vls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vls *VisitLogSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VisitLogSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vls *VisitLogSelect) StringsX(ctx context.Context) []string {
	v, err := vls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vls *VisitLogSelect) StringX(ctx context.Context) string {
	v, err := vls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VisitLogSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vls *VisitLogSelect) IntsX(ctx context.Context) []int {
	v, err := vls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vls *VisitLogSelect) IntX(ctx context.Context) int {
	v, err := vls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VisitLogSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vls *VisitLogSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vls *VisitLogSelect) Float64X(ctx context.Context) float64 {
	v, err := vls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VisitLogSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vls *VisitLogSelect) BoolsX(ctx context.Context) []bool {
	v, err := vls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vls *VisitLogSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{visitlog.Label}
	default:
		err = fmt.Errorf("ent: VisitLogSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vls *VisitLogSelect) BoolX(ctx context.Context) bool {
	v, err := vls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vls *VisitLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vls.sql.Query()
	if err := vls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
