// Code generated by entc, DO NOT EDIT.

package url

import (
	"time"
)

const (
	// Label holds the string label denoting the url type in the database.
	Label = "url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldCurrentTimes holds the string denoting the current_times field in the database.
	FieldCurrentTimes = "current_times"
	// FieldMaxTimes holds the string denoting the max_times field in the database.
	FieldMaxTimes = "max_times"
	// FieldExpireAt holds the string denoting the expire_at field in the database.
	FieldExpireAt = "expire_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeLogs holds the string denoting the logs edge name in mutations.
	EdgeLogs = "logs"
	// Table holds the table name of the url in the database.
	Table = "url"
	// LogsTable is the table that holds the logs relation/edge.
	LogsTable = "log"
	// LogsInverseTable is the table name for the VisitLog entity.
	// It exists in this package in order to avoid circular dependency with the "visitlog" package.
	LogsInverseTable = "log"
	// LogsColumn is the table column denoting the logs relation/edge.
	LogsColumn = "url_logs"
)

// Columns holds all SQL columns for url fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldPath,
	FieldCurrentTimes,
	FieldMaxTimes,
	FieldExpireAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// DefaultCurrentTimes holds the default value on creation for the "current_times" field.
	DefaultCurrentTimes int
	// DefaultMaxTimes holds the default value on creation for the "max_times" field.
	DefaultMaxTimes int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
